language: go

go:
  - master

os:
  - linux

dist: trusty

before_install:
  - sudo apt-get -qq update
  
install:
  - go get github.com/deckarep/golang-set
  - go get github.com/nhoya/goPwned
  - go get github.com/jessevdk/go-flags
  - go get gopkg.in/src-d/go-git.v4
  - go get github.com/jaytaylor/html2text
  - go get gopkg.in/ns3777k/go-shodan.v2/shodan
  - go get golang.org/x/oauth2
  - go get github.com/google/go-github/github
  - cd src && go build -o gOSINT
